#+TITLE: Manage AWS EC2 instances from Emacs

This is very much a package that is designed for my use case. If there is any interest in this at all, I can cleanup the code base, make the interactions more consistent, and make this presentable to the public.

* Install

If you use =straight.el= and =use-package= you can install this with the following command. At some point I'll maybe upload this to melpa and then it'll be easier to install.

#+begin_src emacs-lisp
(use-package ec2
  :straight (ec2 :type git :host github :repo "sgpthomas/ec2.el"))
#+end_src

You'll also need to install and configure the =awscli= tool. Follow Amazon's instructions for that: [[https://aws.amazon.com/cli/][instructions]].

* Setup

The main command is =ec2/dashboard=. Bind this to something convenient, or just call with =M-x ec2/dashboard=.

Running this command will open up a buffer called =*aws*=. In the buffer, pressing =r= will reload the buffer with potentially new information. Right now, you have to press this after most operations. Reloading does not happen automatically.

At the top should be AMI's that you have defined. If you don't have any AMI's defined, you'll want to do that separately (probably using the web interface).

Pressing =tab= on one of the images will bring up a transient buffer with more commands. For AMI's, this will let you configure the security group, number of instances to launch, the instance type, and the key pair to use.

Once you have instances running, they'll appear under the =Instances= header. Pressing =tab= on any instance will bring up more options. Running instances have more options.
